import type {
  Citizen,
  CommitteeItem,
  DisputeRequest,
  Elder,
  LegalCase,
  Office,
  SanaNotice,
  SulhSession,
  VaultDoc,
} from "./types";

export const citizen: Citizen = {
  name: "سارا احمدی",
  nationalId: "۰۰۸۹۳۴۱۲۵۶",
  city: "تهران",
  phone: "۰۹۱۲۳۴۵۶۷۸۹",
};

export const offices: Office[] = [
  {
    id: "off-teh",
    city: "تهران",
    title: "دفتر نمایندگی تهران — آزمایشی",
    manager: "خانم ناهید معین",
    address: "خیابان خردمند جنوبی، پلاک ۴۲",
    capacity: 40,
    active: 18,
    phone: "۰۲۱۸۸۳۳۰۰۱۲",
    status: "pilot",
  },
  {
    id: "off-msh",
    city: "مشهد",
    title: "دفتر نمایندگی مشهد — آزمایشی",
    manager: "مهدی صالحی",
    address: "بلوار سجاد، نبش دانش‌غربی",
    capacity: 24,
    active: 9,
    phone: "۰۵۱۳۷۶۶۱۰۲۰",
    status: "pilot",
  },
  {
    id: "off-esf",
    city: "اصفهان",
    title: "دفتر نمایندگی اصفهان — آزمایشی",
    manager: "لیلا جعفری",
    address: "خیابان چهارباغ بالا",
    capacity: 20,
    active: 7,
    phone: "۰۳۱۳۶۲۲۸۴۱۰",
    status: "pilot",
  },
  {
    id: "off-shr",
    city: "شیراز",
    title: "دفتر نمایندگی شیراز — آزمایشی",
    manager: "کامران رستمی",
    address: "خیابان زند، ساختمان عدل",
    capacity: 16,
    active: 5,
    phone: "۰۷۱۳۲۳۴۵۶۰۰",
    status: "pilot",
  },
  {
    id: "off-tbz",
    city: "تبریز",
    title: "دفتر نمایندگی تبریز — آزمایشی",
    manager: "رؤیا نیکنام",
    address: "ولیعصر، برج دادگستر",
    capacity: 16,
    active: 4,
    phone: "۰۴۱۳۳۳۰۱۲۴۵",
    status: "pilot",
  },
];

export const elders: Elder[] = [
  {
    id: "el-nouri",
    name: "حاج عبدالله نوری",
    domain: "family",
    domainsLabel: "خانواده، مهریه، نفقه",
    city: "تهران",
    years: 42,
    bio: "چهل سال میانجی‌گری در اختلافات خانوادگی؛ مورد تأیید معاونت حل اختلاف استان تهران.",
    approvedBy: "معاونت حل اختلاف استان تهران",
    sessions: 610,
    settlementRate: 78,
  },
  {
    id: "el-kamali",
    name: "دکتر فرهاد کمالی",
    domain: "contract",
    domainsLabel: "قراردادهای تجاری و شرکت‌ها",
    city: "تهران",
    years: 24,
    bio: "سابقه داوری اتاق بازرگانی و سازش در اختلافات قراردادی متوسط.",
    approvedBy: "کمیته حقوقی مؤسسه زندگی",
    sessions: 190,
    settlementRate: 71,
  },
  {
    id: "el-mosavi",
    name: "بانو زهرا موسوی",
    domain: "family",
    domainsLabel: "امور زنان و خانواده",
    city: "مشهد",
    years: 19,
    bio: "تمرکز بر سازش محرمانه در دعاوی خانوادگی با حفظ کرامت طرفین.",
    approvedBy: "معاونت حل اختلاف استان خراسان رضوی",
    sessions: 240,
    settlementRate: 81,
  },
  {
    id: "el-bagheri",
    name: "استاد کریم باقری",
    domain: "labor",
    domainsLabel: "کار، بیمه، اخراج",
    city: "اصفهان",
    years: 31,
    bio: "ریش‌سفید حوزه کارگری؛ آشنا با رویه هیئت‌های تشخیص و حل اختلاف کار.",
    approvedBy: "کمیته حقوقی مؤسسه زندگی",
    sessions: 320,
    settlementRate: 69,
  },
  {
    id: "el-rezaei",
    name: "شیخ محمود رضایی",
    domain: "neighbor",
    domainsLabel: "املاک، دیوار مشاع، همسایگی",
    city: "شیراز",
    years: 38,
    bio: "سازش در اختلافات محلی و ثبتی محله‌محور؛ مورد وثوق دفاتر اسناد.",
    approvedBy: "معاونت حل اختلاف استان فارس",
    sessions: 450,
    settlementRate: 84,
  },
  {
    id: "el-taheri",
    name: "مهندس ناصر طاهری",
    domain: "property",
    domainsLabel: "پیمانکاری و ساخت‌وساز",
    city: "تبریز",
    years: 22,
    bio: "میانجی اختلافات پیمان و تأخیر تحویل در پروژه‌های ساختمانی.",
    approvedBy: "کمیته حقوقی مؤسسه زندگی",
    sessions: 110,
    settlementRate: 66,
  },
];

export const cases: LegalCase[] = [
  {
    id: "c-check",
    title: "مطالبه وجه چک برگشتی — پارس تجارت",
    summary:
      "یک فقره چک عهده بانک ملت به مبلغ یک میلیارد و دویست میلیون ریال برگشت شده است. صادرکننده شرکت پارس تجارت است.",
    domain: "check",
    track: "dispute",
    status: "dispute",
    city: "تهران",
    parties: ["سارا احمدی", "شرکت پارس تجارت"],
    createdAt: "2026-08-18T09:00:00.000Z",
    deadline: "2026-09-12T00:00:00.000Z",
    sanaTracking: "۱۴۰۵۰۸۲۲۰۰۸۴۱۲",
    branchId: "شعبه خصوصی ۲ تهران",
    officeId: "off-teh",
    events: [
      {
        id: "e1",
        at: "2026-08-18T09:00:00.000Z",
        kind: "created",
        title: "ثبت موضوع در داشبورد زندگی",
        detail: "تشخیص هوشمند: اسناد تجاری / مسیر حل اختلاف خصوصی.",
      },
      {
        id: "e2",
        at: "2026-08-18T09:04:00.000Z",
        kind: "ai",
        title: "تحلیل مسیر",
        detail: "با توجه به مبلغ و وجود گواهی عدم پرداخت، ارجاع به شعبه خصوصی مناسب‌تر از سازش صرف است.",
      },
      {
        id: "e3",
        at: "2026-08-19T11:20:00.000Z",
        kind: "branch",
        title: "تخصیص شعبه حل اختلاف بخش خصوصی",
        detail: "دفتر تهران — شعبه خصوصی ۲. ابلاغ از طریق ثنا صادر شد.",
      },
      {
        id: "e4",
        at: "2026-08-20T08:12:00.000Z",
        kind: "sana",
        title: "ابلاغ ثنا به طرفین",
        detail: "شماره پیگیری ۱۴۰۵۰۸۲۲۰۰۸۴۱۲",
      },
    ],
    documentIds: ["d-check", "d-cert", "d-id"],
  },
  {
    id: "c-wall",
    title: "اختلاف دیوار مشاع پلاک ۱۲۲۲",
    summary:
      "همسایه بدون رضایت، دیوار مشاع حیاط را تخریب و در محل پنجره نصب کرده است. موضوع قابلیت سازش محلی دارد.",
    domain: "neighbor",
    track: "sulh",
    status: "intake",
    city: "تهران",
    parties: ["سارا احمدی", "حسین کرمی"],
    createdAt: "2026-09-01T14:10:00.000Z",
    events: [
      {
        id: "w1",
        at: "2026-09-01T14:10:00.000Z",
        kind: "created",
        title: "ثبت موضوع",
        detail: "پیشنهاد سامانه: صلح و سازش با ریش‌سفید حوزه همسایگی.",
      },
      {
        id: "w2",
        at: "2026-09-01T14:12:00.000Z",
        kind: "ai",
        title: "ارزیابی سازش‌پذیری",
        detail: "اختلاف غیرکیفری، طرفین همسایه، سابقه خصومت شدید گزارش نشده. مناسب ریش‌سفید.",
      },
    ],
    documentIds: ["d-deed", "d-photo"],
  },
  {
    id: "c-mahr",
    title: "مطالبه مهریه و نفقه معوق",
    summary:
      "زوجه مهریه عندالمطالبه و نفقه شش ماه را مطالبه می‌کند. زوج آمادگی سازش مشروط دارد.",
    domain: "family",
    track: "sulh",
    status: "sulh",
    city: "تهران",
    parties: ["سارا احمدی", "رضا احمدی"],
    createdAt: "2026-07-22T10:00:00.000Z",
    deadline: "2026-09-18T00:00:00.000Z",
    elderId: "el-nouri",
    events: [
      {
        id: "m1",
        at: "2026-07-22T10:00:00.000Z",
        kind: "created",
        title: "پذیرش پرونده خانوادگی",
      },
      {
        id: "m2",
        at: "2026-07-24T16:00:00.000Z",
        kind: "sulh",
        title: "ارجاع به حاج عبدالله نوری",
        detail: "ریش‌سفید خانواده؛ جلسه اول برگزار شد. ادامه در ۱۸ شهریور.",
      },
      {
        id: "m3",
        at: "2026-08-10T12:00:00.000Z",
        kind: "session",
        title: "جلسه سازش نخست",
        detail: "توافق اولیه بر تقسیط مهریه؛ نفقه در حال مذاکره.",
      },
    ],
    documentIds: ["d-nikah", "d-draft-sulh"],
  },
];

export const documents: VaultDoc[] = [
  {
    id: "d-check",
    title: "تصویر چک عهده بانک ملت",
    kind: "سند تجاری",
    caseId: "c-check",
    source: "upload",
    pages: 1,
    addedAt: "2026-08-18T09:01:00.000Z",
    summary: "چک به شماره ۷۴۴۲۱۹، مبلغ ۱٬۲۰۰٬۰۰۰٬۰۰۰ ریال، سررسید ۱۴۰۵/۰۵/۲۰.",
  },
  {
    id: "d-cert",
    title: "گواهی عدم پرداخت",
    kind: "گواهی بانکی",
    caseId: "c-check",
    source: "upload",
    pages: 2,
    addedAt: "2026-08-18T09:02:00.000Z",
    summary: "صادر شده از شعبه بانک ملت کریمخان.",
  },
  {
    id: "d-id",
    title: "کارت ملی و شناسنامه",
    kind: "هویت",
    source: "upload",
    pages: 2,
    addedAt: "2026-07-01T08:00:00.000Z",
    summary: "مدارک هویتی دارنده حساب داشبورد.",
  },
  {
    id: "d-deed",
    title: "سند مالکیت پلاک ۱۲۲۲",
    kind: "سند رسمی",
    caseId: "c-wall",
    source: "upload",
    pages: 4,
    addedAt: "2026-09-01T14:11:00.000Z",
    summary: "ششدانگ یک واحد مسکونی، عرصه مشاع.",
  },
  {
    id: "d-photo",
    title: "گزارش تصویری دیوار مشاع",
    kind: "مستند",
    caseId: "c-wall",
    source: "upload",
    pages: 3,
    addedAt: "2026-09-01T14:11:30.000Z",
    summary: "وضع موجود پس از تخریب و نصب پنجره.",
  },
  {
    id: "d-nikah",
    title: "عقدنامه رسمی",
    kind: "سند نکاح",
    caseId: "c-mahr",
    source: "upload",
    pages: 2,
    addedAt: "2026-07-22T10:05:00.000Z",
    summary: "مهریه عندالمطالبه: ۱۴ سکه بهار آزادی.",
  },
  {
    id: "d-draft-sulh",
    title: "پیش‌نویس سازش‌نامه مهریه",
    kind: "سازش‌نامه",
    caseId: "c-mahr",
    source: "draft",
    pages: 3,
    addedAt: "2026-08-11T09:00:00.000Z",
    summary: "تقسیط در ۱۲ ماه؛ در انتظار تأیید طرفین و معاونت حل اختلاف.",
  },
  {
    id: "d-articles",
    title: "پیش‌نویس اساسنامه مؤسسه زندگی",
    kind: "اساسنامه",
    source: "draft",
    pages: 18,
    addedAt: "2026-09-04T07:00:00.000Z",
    summary: "نسخه مقدمه برای ثبت شخصیت حقوقی مؤسسه مرکزی و شبکه فرانشیز.",
  },
];

export const sanaNotices: SanaNotice[] = [
  {
    id: "s1",
    title: "ابلاغ تعیین شعبه حل اختلاف خصوصی",
    kind: "branch",
    body: "پرونده مطالبه وجه چک به شعبه خصوصی ۲ دفتر تهران ارجاع شد. حضور در جلسه الزامی است.",
    at: "2026-08-20T08:12:00.000Z",
    deadline: "2026-09-12T00:00:00.000Z",
    caseId: "c-check",
    tracking: "۱۴۰۵۰۸۲۲۰۰۸۴۱۲",
    read: true,
  },
  {
    id: "s2",
    title: "اخطار مهلت ارائه اصل چک",
    kind: "deadline",
    body: "اصل چک و گواهی عدم پرداخت باید تا مهلت مقرر در دفتر شعبه تودیع شود.",
    at: "2026-08-28T10:00:00.000Z",
    deadline: "2026-09-08T00:00:00.000Z",
    caseId: "c-check",
    tracking: "۱۴۰۵۰۸۲۸۰۰۹۱۰۰",
    read: false,
  },
  {
    id: "s3",
    title: "احضاریه جلسه سازش خانوادگی",
    kind: "summons",
    body: "جلسه دوم صلح و سازش با حاج عبدالله نوری در دفتر تهران.",
    at: "2026-09-02T09:40:00.000Z",
    deadline: "2026-09-18T00:00:00.000Z",
    caseId: "c-mahr",
    tracking: "۱۴۰۵۰۹۰۲۰۰۴۴۱۸",
    read: false,
  },
  {
    id: "s4",
    title: "اطلاعیه اتصال حساب ثنا",
    kind: "notice",
    body: "حساب ثنا شما به داشبورد زندگی متصل شد. ابلاغ‌های آتی به‌صورت یکپارچه نمایش داده می‌شود.",
    at: "2026-07-15T12:00:00.000Z",
    tracking: "۱۴۰۵۰۷۱۵۰۰۰۰۰۱",
    read: true,
  },
  {
    id: "s5",
    title: "رأی سازش قابل اجرا — نمونه",
    kind: "ruling",
    body: "نمونه رأی سازش که پس از تأیید معاونت حل اختلاف استان قابلیت اجرا پیدا می‌کند.",
    at: "2026-06-01T08:00:00.000Z",
    tracking: "۱۴۰۵۰۶۰۱۰۰۱۱۱۱",
    read: true,
  },
];

export const sulhSessions: SulhSession[] = [
  {
    id: "su-mahr",
    caseId: "c-mahr",
    elderId: "el-nouri",
    title: "سازش مهریه و نفقه",
    domain: "family",
    status: "scheduled",
    scheduledAt: "2026-09-18T12:00:00.000Z",
    city: "تهران",
    notes: "توافق اولیه بر تقسیط مهریه. نفقه هنوز محل نزاع است.",
  },
  {
    id: "su-wall",
    caseId: "c-wall",
    elderId: "el-rezaei",
    title: "سازش دیوار مشاع — در انتظار تأیید طرف مقابل",
    domain: "neighbor",
    status: "requested",
    city: "تهران",
    notes: "پیشنهاد ارجاع به ریش‌سفید حوزه همسایگی. طرف مقابل هنوز پاسخ نداده.",
  },
];

export const disputes: DisputeRequest[] = [
  {
    id: "dr-check",
    caseId: "c-check",
    officeId: "off-teh",
    branchLabel: "شعبه خصوصی ۲ تهران",
    city: "تهران",
    status: "notified",
    sanaTracking: "۱۴۰۵۰۸۲۲۰۰۸۴۱۲",
    createdAt: "2026-08-19T11:20:00.000Z",
    sessionAt: "2026-09-12T09:00:00.000Z",
  },
];

export const committeeItems: CommitteeItem[] = [
  {
    id: "ci-1",
    title: "صلاحیت شعبه خصوصی در دعاوی چک پس از اصلاح قانون صدور چک",
    body: "با توجه به مسائل مستحدثه ناشی از سامانه صیاد و تغییرات صلاحیت، کمیته باید رویه واحد برای ارجاع به شعبه خصوصی تدوین کند.",
    status: "review",
    domain: "check",
    raisedAt: "2026-08-30T10:00:00.000Z",
    from: "دفتر تهران",
  },
  {
    id: "ci-2",
    title: "تفکیک حقوقی صلح و سازش از مشاوره و وکالت",
    body: "ضرورت آیین‌نامه داخلی: ریش‌سفید حق تنظیم دادخواست و دریافت حق‌الوکاله ندارد؛ خروجی صرفاً سازش‌نامه است.",
    status: "opinion",
    domain: "other",
    raisedAt: "2026-08-12T10:00:00.000Z",
    from: "ریاست پروژه",
    opinion:
      "سه مسیر باید در رابط کاربری و قراردادها کاملاً جدا بماند. صلح و سازش با هماهنگی معاونت حل اختلاف استان ضمانت اجرایی می‌گیرد و نباید با وکالت خلط شود.",
  },
  {
    id: "ci-3",
    title: "اتصال API ثنا برای ابلاغ شعبه بخش خصوصی",
    body: "مدل داده ابلاغ «تعیین شعبه خصوصی» هنوز در سند تحول به‌صورت سکو تعریف شده؛ کمیته باید فیلدهای الزامی را نهایی کند.",
    status: "open",
    domain: "other",
    raisedAt: "2026-09-03T08:00:00.000Z",
    from: "تیم فنی",
  },
  {
    id: "ci-4",
    title: "مسائل مستحدثه داوری آنلاین در قراردادهای مصرف",
    body: "موقعیت زمانی و مکانی قراردادهای الکترونیک، صلاحیت و نحوه ابلاغ را تغییر می‌دهد.",
    status: "open",
    domain: "contract",
    raisedAt: "2026-09-04T11:00:00.000Z",
    from: "کمیته حقوقی",
  },
];
