/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCasesRouteImport } from './routes/app/cases'
import { Route as AppCommitteeRouteImport } from './routes/app/committee'
import { Route as AppCompanyRouteImport } from './routes/app/company'
import { Route as AppConsultRouteImport } from './routes/app/consult'
import { Route as AppDisputeRouteImport } from './routes/app/dispute'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppDraftRouteImport } from './routes/app/draft'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppOfficesRouteImport } from './routes/app/offices'
import { Route as AppSanaRouteImport } from './routes/app/sana'
import { Route as AppSulhRouteImport } from './routes/app/sulh'
import { Route as AppCasesIdRouteImport } from './routes/app/cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitteeRoute = AppCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultRoute = AppConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputeRoute = AppDisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftRoute = AppDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOfficesRoute = AppOfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => AppRoute,
} as any)
const AppSanaRoute = AppSanaRouteImport.update({
  id: '/sana',
  path: '/sana',
  getParentRoute: () => AppRoute,
} as any)
const AppSulhRoute = AppSulhRouteImport.update({
  id: '/sulh',
  path: '/sulh',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIdRoute = AppCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/committee': typeof AppCommitteeRoute
  '/app/company': typeof AppCompanyRoute
  '/app/consult': typeof AppConsultRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/draft': typeof AppDraftRoute
  '/app/new': typeof AppNewRoute
  '/app/offices': typeof AppOfficesRoute
  '/app/sana': typeof AppSanaRoute
  '/app/sulh': typeof AppSulhRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/committee': typeof AppCommitteeRoute
  '/app/company': typeof AppCompanyRoute
  '/app/consult': typeof AppConsultRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/draft': typeof AppDraftRoute
  '/app/new': typeof AppNewRoute
  '/app/offices': typeof AppOfficesRoute
  '/app/sana': typeof AppSanaRoute
  '/app/sulh': typeof AppSulhRoute
  '/app': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/committee': typeof AppCommitteeRoute
  '/app/company': typeof AppCompanyRoute
  '/app/consult': typeof AppConsultRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/draft': typeof AppDraftRoute
  '/app/new': typeof AppNewRoute
  '/app/offices': typeof AppOfficesRoute
  '/app/sana': typeof AppSanaRoute
  '/app/sulh': typeof AppSulhRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/cases'
    | '/app/committee'
    | '/app/company'
    | '/app/consult'
    | '/app/dispute'
    | '/app/documents'
    | '/app/draft'
    | '/app/new'
    | '/app/offices'
    | '/app/sana'
    | '/app/sulh'
    | '/app/'
    | '/app/cases/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/cases'
    | '/app/committee'
    | '/app/company'
    | '/app/consult'
    | '/app/dispute'
    | '/app/documents'
    | '/app/draft'
    | '/app/new'
    | '/app/offices'
    | '/app/sana'
    | '/app/sulh'
    | '/app'
    | '/app/cases/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/cases'
    | '/app/committee'
    | '/app/company'
    | '/app/consult'
    | '/app/dispute'
    | '/app/documents'
    | '/app/draft'
    | '/app/new'
    | '/app/offices'
    | '/app/sana'
    | '/app/sulh'
    | '/app/'
    | '/app/cases/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/committee': {
      id: '/app/committee'
      path: '/committee'
      fullPath: '/app/committee'
      preLoaderRoute: typeof AppCommitteeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/company': {
      id: '/app/company'
      path: '/company'
      fullPath: '/app/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consult': {
      id: '/app/consult'
      path: '/consult'
      fullPath: '/app/consult'
      preLoaderRoute: typeof AppConsultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispute': {
      id: '/app/dispute'
      path: '/dispute'
      fullPath: '/app/dispute'
      preLoaderRoute: typeof AppDisputeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/draft': {
      id: '/app/draft'
      path: '/draft'
      fullPath: '/app/draft'
      preLoaderRoute: typeof AppDraftRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offices': {
      id: '/app/offices'
      path: '/offices'
      fullPath: '/app/offices'
      preLoaderRoute: typeof AppOfficesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sana': {
      id: '/app/sana'
      path: '/sana'
      fullPath: '/app/sana'
      preLoaderRoute: typeof AppSanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sulh': {
      id: '/app/sulh'
      path: '/sulh'
      fullPath: '/app/sulh'
      preLoaderRoute: typeof AppSulhRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases/$id': {
      id: '/app/cases/$id'
      path: '/$id'
      fullPath: '/app/cases/$id'
      preLoaderRoute: typeof AppCasesIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesIdRoute: typeof AppCasesIdRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesIdRoute: AppCasesIdRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppCommitteeRoute: typeof AppCommitteeRoute
  AppCompanyRoute: typeof AppCompanyRoute
  AppConsultRoute: typeof AppConsultRoute
  AppDisputeRoute: typeof AppDisputeRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDraftRoute: typeof AppDraftRoute
  AppNewRoute: typeof AppNewRoute
  AppOfficesRoute: typeof AppOfficesRoute
  AppSanaRoute: typeof AppSanaRoute
  AppSulhRoute: typeof AppSulhRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRouteWithChildren,
  AppCommitteeRoute: AppCommitteeRoute,
  AppCompanyRoute: AppCompanyRoute,
  AppConsultRoute: AppConsultRoute,
  AppDisputeRoute: AppDisputeRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDraftRoute: AppDraftRoute,
  AppNewRoute: AppNewRoute,
  AppOfficesRoute: AppOfficesRoute,
  AppSanaRoute: AppSanaRoute,
  AppSulhRoute: AppSulhRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
